#!/usr/bin/env bash

BR_PATH="$HOME/.config/broot/launcher/bash/br"
# shellcheck source=.config/broot/launcher/bash/br
[[ -f $BR_PATH ]] && source "$BR_PATH"

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
